[package]
name = "static-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.5"
tokio = { version = "1.47.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["compression-br", "compression-gzip", "cors", "fs"] }
